---
title: "eds221-day4-comp"
author: "Jake Eisaguirre"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)


```

```{r}
quarter_splits <- c(1.0, 1.1, 1.2, 1.1, 1.4, 1.5, 1.6, 1.4)

half_splits <- vector(mode = "numeric", length = length(quarter_splits) - 1)

for (i in seq_along(quarter_splits) - 1) {
  q <- print(quarter_splits[i] + quarter_splits[i + 1])
  half_splits[i] <- q           
}


```

## Basic function structure practice 

```{r}

birddog_sum <- function(bird, dog) {
  
  if (bird > 50) {
    stop("birds cant be greater than 50")
  }
  
  if (bird < 10) {
    message("cool little bird")
  }
  
  if (dog < 0) {
    warning("can a dog be less than 0 pounds?")
  }
  
  add_birddog <- bird + dog
  return(add_birddog)
}

birddog_sum(bird = 6, dog = 5)
birddog_sum(bird = 6, dog = -5)





```


```{r}
say_hello <- function(friend, weekday) {
  print(paste("Hello", friend, "have a great", weekday))
}

say_hello(friend = "Alex", weekday = "Thursday")


```

### print vs return

```{r}

find_multiple <- function(a, b) {
  my_multiplication <- a * b
  print(my_multiplication)
}

find_multiple(a = 10, b = 6)



```

### functions with conditions
```{r}

animal_age <- function(animal, age) {
  
  if (!animal %in% c("dog", "goat")){
    stop("Animal must be a dog or a goat")
  }
  
  if (animal == "dog"){
    creature_age <- age * 7
  }
  
  else if (animal == "goat"){
    creature_age <- age *4.7
  }
  
  return(creature_age)
}



animal_age(animal = "goat", age = 13)

#animal_age(animal = "zebra", age = 13)



```
### %in% operator

```{r}

Adel_Gent <- penguins %>% 
  filter(species %in% c("Adelie", "Gentoo"))

### dont do below for data wrangling VERY WRONG
adel_gent_wrong <- penguins %>% 
  filter(species == c("Adelie", "Gentoo"))
```

### functions with forloops

```{r}

df_means <- function(df) {
  for (i in seq_along(df)) {
    col_mean <- mean(df[[i]], na.rm = TRUE)
    column_name <- colnames(df[i])
    print(paste("the mean of", column_name, "is", col_mean))
  }
}

df_means(df = mtcars)

#columnnames(df[i]) wil return that column name as a string

```

```{r}
#make a subset of only structual size variable from the penguins dataset chinstrap

chinstrap_sizes <- penguins %>% 
  filter(species %in% c("Chinstrap")) %>% 
  select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)
 
df_means(chinstrap_sizes) 
df_means(penguins)


```
## condition to check class of an input
```{r}

lunchtime <- function(tacos, price_per) {
  
  if(is.numeric(tacos)== FALSE){
    stop("you must input a number of tacos")
  }
  
  total_price <- tacos * price_per
  return(total_price)
}

lunchtime(tacos = "bananas", price_per = 2.50)


```

## example: use values from a df to calculate something based on user input
```{r}

# calculate the groundwater transport rate

gw_rate <- function(site){
  
  gw_depth_slope <- data.frame(sitename = c("mountain", "prairie", "desert", "beach"),
                               depth = c(32, 41, 63, 2),
                               slope = c(11.2, 0.4, 0.8, 2.6))
  
  site_select <- filter(gw_depth_slope, sitename == site)
  
  transport <- 1.4 * site_select$slope + 3.6 * site_select$depth
  
  return(transport)
  
}

gw_rate(site = "beach")


```

## same thing as above but using switch function

```{r}

gw_rate_switch <- function(site){
  
  gw_slope_depth <- switch (site,
                            "mountain" = c(32, 11.2),
                            "prairie" = c(41, 0.4),
                            "desert" = c(63, 0.8),
                            "beach" = c(2, 2.6))
  
  transport_rate <- 1.4 * gw_slope_depth[2] + 3.6 * gw_slope_depth[1]
  
  return(transport_rate)
}

gw_rate_switch(site = "beach")

```

## logistic growth equation function

```{r}

logistic_growth <- function(K, N0, r, time) {
  
  Nt <- K / (1 + ((K-N0) / N0) * exp(-r * time))
  
  print(Nt)
  
}

logistic_growth(K = 5000, N0 = 200, r = 0.43, time = 6)

time_vec <- seq(from = 0, to = 35, by = 0.1)

bacterial_growth <- logistic_growth(K = 5000, N0= 200, r = 0.43, time = time_vec)

bacterial_df <- data.frame(time_vec, bacterial_growth)

ggplot(data = bacterial_df, aes(x = time_vec, y = bacterial_growth)) +
  geom_point()



```

```{r}

r_seq <- seq(from = 0.20, to = 0.40, by = 0.01)

time_vec <- seq(from = 0, to = 35, by = 0.1)

out_matrix <- matrix(ncol = length(r_seq), nrow = length(time_vec))

#N0 = 100, K = 6000

for (i in seq_along(r_seq)){
  
  for (j in seq_along(time_vec)) {
    
    pop <- logistic_growth(K = 6000, N0 = 100, r = r_seq[i], time = time_vec[j])
    
    out_matrix[j, i] <- pop
  }
  
}

#wrangling

out_df <- data.frame(time = time_vec, out_matrix)

#update column names

colnames(out_df) <- c("time", paste0("gr_", r_seq))

# make a long form (tidy verson) of this data

out_df_long <- out_df %>% 
  pivot_longer(-time, names_to = "growth_rate", values_to = "population")

ggplot(data = out_df_long, aes(x = time, y = population)) +
  geom_line(aes(color = growth_rate))

```

